version: '2'
services:
  db:
    hostname: db
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/sql:/var/lib/mysql
    networks:
      - 10bnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/test?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      DATABASE_USER: root
      DATABASE_PASSWORD: root
    networks:
      - 10bnet
networks:
  10bnet:
    driver: bridge
